
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int parizquierdo = 7;
  public static final int menorque = 31;
  public static final int menos = 3;
  public static final int rstring = 17;
  public static final int rread = 80;
  public static final int puntoycoma = 10;
  public static final int rtoInt = 69;
  public static final int rstatic = 65;
  public static final int punto = 72;
  public static final int corderecho = 59;
  public static final int menorigualque = 33;
  public static final int rfor = 47;
  public static final int rint = 13;
  public static final int mas = 2;
  public static final int cadena = 25;
  public static final int dospuntos = 52;
  public static final int rprotected = 62;
  public static final int rdouble = 14;
  public static final int rinstanceof = 79;
  public static final int umenos = 82;
  public static final int interrogacion = 53;
  public static final int rprintln = 28;
  public static final int rtoDouble = 68;
  public static final int parderecho = 8;
  public static final int or = 37;
  public static final int mayorque = 32;
  public static final int caracter = 26;
  public static final int rextends = 71;
  public static final int id = 27;
  public static final int rtrue = 23;
  public static final int rboolean = 16;
  public static final int corizquierdo = 58;
  public static final int rchar = 15;
  public static final int menosmenos = 55;
  public static final int rread_file = 77;
  public static final int rnew = 60;
  public static final int rfalse = 24;
  public static final int rfinal = 66;
  public static final int rvoid = 20;
  public static final int llaveder = 12;
  public static final int relse = 42;
  public static final int and = 38;
  public static final int rabstract = 64;
  public static final int rgraph = 75;
  public static final int mayorigualque = 34;
  public static final int rdefault = 51;
  public static final int rdo = 48;
  public static final int xor = 39;
  public static final int rnull = 73;
  public static final int division = 5;
  public static final int EOF = 0;
  public static final int rclass = 18;
  public static final int rsuper = 76;
  public static final int rswitch = 49;
  public static final int rpublic = 61;
  public static final int rreturn = 57;
  public static final int diferenteque = 36;
  public static final int rprinttabla = 30;
  public static final int potencia = 6;
  public static final int rwhile = 43;
  public static final int error = 1;
  public static final int rgraficarentornos = 81;
  public static final int entero = 21;
  public static final int rwrite_file = 78;
  public static final int rpow = 56;
  public static final int rbreak = 44;
  public static final int rimport = 74;
  public static final int igualigual = 35;
  public static final int rif = 41;
  public static final int rcase = 50;
  public static final int por = 4;
  public static final int rprivate = 63;
  public static final int rprint = 29;
  public static final int coma = 19;
  public static final int modulo = 46;
  public static final int not = 40;
  public static final int doble = 22;
  public static final int igual = 9;
  public static final int rcontinue = 45;
  public static final int rstr = 67;
  public static final int masmas = 54;
  public static final int llaveizq = 11;
  public static final int rtoChar = 70;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "division",
  "potencia",
  "parizquierdo",
  "parderecho",
  "igual",
  "puntoycoma",
  "llaveizq",
  "llaveder",
  "rint",
  "rdouble",
  "rchar",
  "rboolean",
  "rstring",
  "rclass",
  "coma",
  "rvoid",
  "entero",
  "doble",
  "rtrue",
  "rfalse",
  "cadena",
  "caracter",
  "id",
  "rprintln",
  "rprint",
  "rprinttabla",
  "menorque",
  "mayorque",
  "menorigualque",
  "mayorigualque",
  "igualigual",
  "diferenteque",
  "or",
  "and",
  "xor",
  "not",
  "rif",
  "relse",
  "rwhile",
  "rbreak",
  "rcontinue",
  "modulo",
  "rfor",
  "rdo",
  "rswitch",
  "rcase",
  "rdefault",
  "dospuntos",
  "interrogacion",
  "masmas",
  "menosmenos",
  "rpow",
  "rreturn",
  "corizquierdo",
  "corderecho",
  "rnew",
  "rpublic",
  "rprotected",
  "rprivate",
  "rabstract",
  "rstatic",
  "rfinal",
  "rstr",
  "rtoDouble",
  "rtoInt",
  "rtoChar",
  "rextends",
  "punto",
  "rnull",
  "rimport",
  "rgraph",
  "rsuper",
  "rread_file",
  "rwrite_file",
  "rinstanceof",
  "rread",
  "rgraficarentornos",
  "umenos"
  };
}

